name: Docker Image CI

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag alfonzso/py-xlate:release-1.0.${{ github.run_number }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: alfonzso/manga-manager:release-0.0.${{ github.run_number }}
        cache-from: type=registry,ref=alfonzso/manga-manager:buildcache
        cache-to: type=registry,ref=alfonzso/manga-manager:buildcache,mode=max
